language: minimal
os: linux
dist: trusty
services:
  - docker
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "jq"
jobs:
  include:
  - stage: test
    script: bash ./scripts/test.sh -v $TRAVIS_TAG -b
  - stage: release
    before_install:
      - pyenv global 3.7.1
      - pip install -U pip
      - pip3 install awscli
      
    before_deploy:
      - openssl aes-256-cbc -K $encrypted_40f37f860686_key -iv $encrypted_40f37f860686_iv -in travis_deploy.enc -out /tmp/travis_deploy -d
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/travis_deploy
      - ssh-add /tmp/travis_deploy
    script: skip
    if: type = push AND tag IS present
    deploy:
      provider: script
      skip_cleanup: true
      script: bash ./scripts/deploy.sh -v $TRAVIS_TAG -n git